autonomoussystem:
    pattern:  /
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:index" }

autonomoussystem_show:
    pattern:  /{id}/show
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:show" }

autonomoussystem_new:
    pattern:  /new
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:new" }

autonomoussystem_create:
    pattern:  /create
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:create" }
    requirements: { _method: post }

autonomoussystem_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:edit" }

autonomoussystem_update:
    pattern:  /{id}/update
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:update" }
    requirements: { _method: post }

autonomoussystem_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:delete" }
    requirements: { _method: post }

#autonomoussystem_parse:
#    pattern:  /{asId}
#    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:parse" }
    
autonomoussystem_parseAll:
    pattern:  /parseAll
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:parseAll" }

autonomoussystem_testing:
    pattern:  /testing
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:testing" }
    
autonomoussystem_serwers:
    pattern:  /{id}/serwers
    defaults: { _controller: "MccASMemberBundle:AutonomousSystem:serwers" }