mcc_as_member_homepage:
    pattern:  /
    defaults: { _controller: MccASMemberBundle:AutonomousSystem:index }

mcc_autonomoussystem:
    resource: "routing/autonomoussystem.yml"
    prefix:   /autonomoussystem

mcc_ip:
    resource: "routing/ip.yml"
    prefix:   /ip

mcc_history:
    resource: "routing/history.yml"
    prefix:   /history

AllAS:
    pattern:  /AllAS
    defaults: { _controller: MccASMemberBundle:AutonomousSystem:parseAsName }

AllIp:
    pattern:  /AllIp
    defaults: { _controller: MccASMemberBundle:Ip:allIp }

MccASMemberBundle_iprange:
    resource: "@MccASMemberBundle/Resources/config/routing/iprange.yml"
    prefix:   /iprange    